# Generated by Django 4.2.5 on 2023-11-12 23:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pitche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=500)),
                ('name_of_supervisor', models.CharField(max_length=50)),
                ('phone_of_supervisor', models.CharField(max_length=11)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitches.city')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitches.manager')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.DateTimeField(default=datetime.datetime(2023, 11, 13, 2, 55, 43, 974088))),
                ('to_hour', models.DateTimeField(default=datetime.datetime(2023, 11, 13, 2, 55, 43, 974088))),
                ('timing', models.CharField(choices=[('one Hour', 'one hour'), ('Tow Hour', 'Tow hour'), ('Three Hour', 'Three hour'), ('Four Hour', 'Four hour')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pitche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitches.pitche')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-from_hour'],
            },
        ),
    ]
